### ISSUE TITLE
would you mind sharing the config/model/default.yaml of the base model in your paper?

### ISSUE THREAD

**Issue by Heisenburger2020** [Aria-K-Alethia/BigCodec#12]
Thank you

**Comment by Aria-K-Alethia** [comment]
Hi,

Here you are.
```yaml
codec_encoder:
  in_channels: 1
  out_channels: 128
  ngf: 32
  n_residual_layers: [3, 3, 3, 3]
  dropout: 0.1
  use_rnn: True
  rnn_bidirectional: False
  rnn_num_layers: 2
  rnn_dropout: 0.0
  up_ratios: [2, 4, 5, 5]
  dilations: [1, 3, 9]
  use_weight_norm: True

codec_decoder:
  in_channels: 128
  upsample_initial_channel: 512
  ngf: 32
  n_residual_layers: [3, 3, 3, 3]
  dropout: 0.1
  use_rnn: True
  rnn_bidirectional: False
  rnn_num_layers: 2
  rnn_dropout: 0.0
  up_ratios: [5, 5, 4, 2] # [2, 5, 5, 4]
  dilations: [1, 3, 9]
  vq_num_quantizers: 1
  vq_dim: 128
  vq_commit_weight: 0.25
  vq_weight_init: False
  vq_full_commit_loss: False
  vq_type: rvq
  quantizer_type: fvq
  codebook_size: 8192
  codebook_dim: 8
  use_weight_norm: True
  quantizer_dropout: 0.0
  dropout_type: linear

mpd:
  periods: [2, 3, 5, 7, 11]
  max_downsample_channels: 512
  channels: 16
  channel_increasing_factor: 2

mstft:
  stft_params:
    fft_sizes: [128, 256, 512, 1024, 2048]
    hop_sizes: [32, 64, 128, 256, 512]
    win_lengths: [128, 256, 512, 1024, 2048]
    window: hann_window
  in_channels: 1
  out_channels: 1
  kernel_sizes: [5, 3]
  channels: 16
  max_downsample_channels: 512
  downsample_scales: [2, 2, 2]
  use_weight_norm: True
  use_complex: False
```
